[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["imagededup", "imagededup.handlers", "imagededup.handlers.metrics", "imagededup.handlers.search", "imagededup.evaluation", "imagededup.methods", "imagededup.utils", "mkdocs"]